version: '3'
services:
  database:
    image: postgres:16
    container_name: weather
    ports:
      - '5432:5432'
    environment:
      - POSTGRES_DB=weather
      - POSTGRES_USER=weather
      - POSTGRES_PASSWORD=weather
